name: 'mdbook-full'
description: >
  Install mdbook with plugins
  svgbob, katex, linkcheck

branding:
  icon: upload-cloud
  color: green

# inputs:
  # pattern:
  #   description: 'file pattern to convert'
  #   required: true
  #   default: '**/*.md'

runs:
  using: "composite"
  steps:
    - name: install mdbook and plugins
      shell: bash
      run: |
        curl -LsSf https://github.com/colibri-coruscans/mdbook-full/releases/download/v0.4.28/mdbook-svgbob.tar.gz -o mdbook-svgbob.tar.gz
        mkdir mdbook-svgbob
        tar xz -f mdbook-svgbob.tar.gz -C mdbook-svgbob
        echo "$PWD/mdbook-svgbob" >> $GITHUB_PATH

        curl -LsSf https://github.com/colibri-coruscans/mdbook-full/releases/download/v0.4.28/mdbook-katex.tar.gz -o mdbook-katex.tar.gz
        mkdir mdbook-katex
        tar xz -f mdbook-katex.tar.gz -C mdbook-katex
        echo "$PWD/mdbook-katex" >> $GITHUB_PATH

        curl -LsSf https://github.com/colibri-coruscans/mdbook-full/releases/download/v0.4.28/mdbook-linkcheck.tar.gz -o mdbook-linkcheck.tar.gz
        mkdir mdbook-linkcheck
        tar xz -f mdbook-linkcheck.tar.gz -C mdbook-linkcheck
        chmod +x mdbook-linkcheck/mdbook-linkcheck
        echo "$PWD/mdbook-linkcheck" >> $GITHUB_PATH

        curl -LsSf https://github.com/colibri-coruscans/mdbook-full/releases/download/v0.4.28/mdbook.tar.gz -o mdbook.tar.gz
        mkdir mdbook
        tar xz  -f mdbook.tar.gz -C mdbook
        echo "$PWD/mdbook" >> $GITHUB_PATH
